spring:
  application:
    name: parImpar
  datasource:
    jdbcUrl:  jdbc:mysql://localhost:3307/spring_batch
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema:  always

app:
  datasource:
    jdbcUrl:  jdbc:mysql://localhost:3307/appSpring
    username: root
    password: root
  file: D://Junior//desenvolvimento//git_local//estudo_SpringBatch//springbatch-parimpar//files//clientes.txt
  fileMultiplosRegistros: D://Junior//desenvolvimento//git_local//estudo_SpringBatch//springbatch-parimpar//files//clientesMultiplosRegistros.txt